version: '3.8'

services:
  streamlit-app:
    build:
      context: .
    ports:
      - "8502:8502"
    volumes:
      - /Users/thyagoluciano/Downloads/dup-canal-participante-api/src/main/java/br/com/nuclea/dupcanalparticipanteapi:/output